### ISSUE TITLE
Add more information to README

### ISSUE THREAD

**Issue by amiller-gh** [nodejs/badges#10]
May be helpful to include more copy about what this working group is, our responsibilities, and the intended impact of this initiative.

**Comment by ryzokuken** [comment]
@amiller-gh I'd love to pick this up, let me know what content to add.

**Comment by amiller-gh** [comment]
@ryzokuken Thank you! We had some asks for more information on what Open Badges are, and the intended impact on the initial README PR: https://github.com/nodejs/badges/pull/1#discussion_r168855422

Will leave it to your discretion for content and format, but I think adding sections for `Open Badges` and `Community Impact` may be a good place to start. 

We're in the early days of this initiative, so any and all ideas for how to make the README more useful for first-time-viewers are welcome! Get them up in PR and we can iterate there 👍
