### ISSUE TITLE
Add Dhruv Jain as _badges_ team member

### ISSUE THREAD

**Issue by maddhruv** [nodejs/badges#11]
Hey @amiller-gh 
can I also be a team member for badges

I am interested in working on this idea

**Comment by amiller-gh** [comment]
Happily! PRd in https://github.com/nodejs/badges/pull/12.

Would love some help with https://github.com/nodejs/badges/issues/4 if you have some free time.

I'm planning to hold the first meeting in the next two weeks. Will ping the team in https://github.com/nodejs/badges/issues/2 when I get that going 👍
