### ISSUE TITLE
Add repo access to team

### ISSUE THREAD

**Issue by maddhruv** [nodejs/badges#15]
Give repository write access to team @nodejs/badges

**Comment by amiller-gh** [comment]
Sorry! Added 👍

**Comment by maddhruv** [comment]
I still can't merge PRs and make changes to the repo! Please check

**Comment by amiller-gh** [comment]
Hmm, everything seems to check out on the settings page. The badges team should have write access and I've confirmed you are a member of the team! Try to merge #14 now that its been flagged as approved?

**Comment by amiller-gh** [comment]
Try again?
