### ISSUE TITLE
2018-04-05 Node.js Badges Meeting

### ISSUE THREAD

**Issue by amiller-gh** [nodejs/badges#16]
## Time

**UTC Thur 05-Apr-2018 15:00 (03:00 PM)**:

| Timezone      | Date/Time             |
|---------------|-----------------------|
| US / Pacific  | Thur 05-Apr-2018 08:00 (08:00 AM) |
| US / Mountain | Thur 05-Apr-2018 9:00 (9:00 AM) |
| US / Central  | Thur 05-Apr-2018 10:00 (10:00 AM) |
| US / Eastern  | Thur 05-Apr-2018 11:00 (11:00 AM) |
| London        | Thur 05-Apr-2018 16:00 (04:00 PM) |
| Amsterdam     | Thur 05-Apr-2018 17:00 (05:00 PM) |
| Moscow        | Thur 05-Apr-2018 18:00 (06:00 PM) |
| Chennai       | Thur 05-Apr-2018 20:30 (8:30 PM) |
| Hangzhou      | Thur 05-Apr-2018 01:00 (11:00 PM) |
| Tokyo         | Fri 06-Apr 2018 00:00 (12:00 AM) |
| Sydney        | Fri 06-Apr-2018 04:00 (01:00 AM) |

Or in your local time:
* https://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Badges+Meeting+2018-04-05&iso=20180405T15
* or http://www.wolframalpha.com/input/?i=03PM+UTC%2C+Apr+05%2C+2018+in+local+time

## Links

* Minutes Google Doc: https://docs.google.com/document/d/1jpeSk5Z2htzStsD-89GP3bBnTzO8HDw5Qz7-rGPCIZU/edit?usp=sharing

## Agenda

* Set Up a Badge Issuer Account #3 
* V1 Badges List #8 
* Badge / Pathway RFC process and template #4
* Node.js Badges Illustration Style Guide #7
* Github + Badger API Integration for Automated Awarding #9
* Future Meetings

### Badges Team Members
- [@amiller-gh](https://github.com/amiller-gh) - **Adam Miller**, Community Committee Champion
- [@maddhruv](https://github.com/maddhruv) - **Dhruv Jain**
- [@ryzokuken](https://github.com/ryzokuken) - **Ujjwal Sharma**
- [@Tiriel](https://github.com/Tiriel) - **Benjamin Zaslavsky**

## Joining the meeting

* link for participants: Will be added a few minutes before meeting starts
* For those who just want to watch: 
* youtube admin page: https://www.youtube.com/my_live_events?filter=scheduled

**Comment by maddhruv** [comment]
Can we shift this on Thursday? April 5

**Comment by amiller-gh** [comment]
If you're able to, sure 👍 @ryzokuken marked himself as available at this time for Thursday.

**Comment by amiller-gh** [comment]
We will have a very hard stop at 9:00 though, that is when the general Community Committee meeting begins.

**Comment by ryzokuken** [comment]
@amiller-gh If anyone of us can't make it on Wed for some reason, then I could free up some time on Thursday instead, it's okay.

**Comment by amiller-gh** [comment]
Updated to Thurs, 15:00-16:00UTC 👍 Look forward to seeing everyone there!

**Comment by ryzokuken** [comment]
@amiller-gh any updates on this? Calendar invites haven't been sent yet, I guess.

Also, the Youtube link is probably not the correct one.

**Comment by amiller-gh** [comment]
@nodejs/badges I don't think we're going to get the Zoom account for this meeting – for today lets use the following and we'll sync up with Tierney later to make sure we have full AV support for the next one:

https://linkedin.bluejeans.com/6734213753/

See you in a few!

**Comment by Tiriel** [comment]
Sorry I couldn't make it, lots to do today :S

**Comment by amiller-gh** [comment]
Meeting minutes merged in #17 👍
