### ISSUE TITLE
First badges team meeting?

### ISSUE THREAD

**Issue by amiller-gh** [nodejs/badges#2]
I'm happy to continue with async communications, but think the project may benefit from an in-person meeting! If we held a meeting for Node.js Badges, who would like to attend? If there is enough interest, I will send out a Doodle to determine the best time.

**Comment by amiller-gh** [comment]
(@Tiriel for visibility 🙂)

**Comment by maddhruv** [comment]
I am ok with a meeting
Lets frame up the agenda to discuss upon and collect some informations

**Comment by amiller-gh** [comment]
Hey all – now that we have four members, I think its about time we set up this meeting!

@Tiriel, @maddhruv, @ryzokuken, please fill out this Doodle poll so we can pick a time that will work for us: https://doodle.com/poll/vq4dc7rix6k6zemm (cc: @bnb and @mhdawson, feel free to attend if you'd like to / have the time)

I've populated the poll with days over the next week and a half after this Wednesday. I'm unfortunately gone this weekend through Monday, so I've removed those as options.

**Comment by amiller-gh** [comment]
Also, this is also an open invitation! Anyone else who happens to be watching the activity in this repo should feel free to fill out the poll as well.

**Comment by bnb** [comment]
@amiller-gh please ping me when you know what time you've settled on - I'll set up a calendar invite + Zoom for y'all. I can livestream it if you want, though I may or may not be able to participate when streaming 😅

**Comment by amiller-gh** [comment]
Looks like the best options are: 

 - Tuesday April 4th, 3:00PM UTC (8:00AM PST)
 - Wednesday April 5th, 3:00PM UTC (8:00AM PST) 
 - Wednesday April 5th, 4:00PM UTC (9:00AM PST)

@Tiriel, I think we're just waiting on you. Do one of the dates above work for you? Let us know and we'll call that the official time.

@bnb, I'm also happy to start learning the Zoom machinery if you'd like an extra pair of hands managing it – I'm amazed at how many CommComm meetings you're able to attend! Ping me on Slack with details if you'd like 👍

**Comment by amiller-gh** [comment]
Okay, I'm going to call it: lets do Wednesday April 5th at 3:00PM UTC if everyone is still free.

@bnb, work your calendar / Zoom magic 👌

**Comment by maddhruv** [comment]
Works great for me!
But shall we decide the agendas for the same

**Comment by amiller-gh** [comment]
I'm in meetings the rest of the day, but will publish an agenda for Wednesday later tonight on github 👍(its 10am right now for me)

We will probably want to review most of the open issues, but specifically I'm hoping to get a final resolution on #3, and move the discussion on #8 forward. We need to develop some consensus on what initial rollout looks like and I think an "in-person" meeting is the correct place for that! We also may want to chat about the logistics of publishing a badge design system and how we can best push work on that forward.

Any topics not covered in current tickets, or mentioned above, that you'd like to see on the agenda?

**Comment by maddhruv** [comment]
I will look into more of open badges before Wednesday! Having exams these days 😫 can't involve much!
The core agenda should be focused over which service/open badge platform we should use and get more deeper into them! #8 v1 rollouts are a following concern!
Also taking suggestions from other core members(TSC, CommComm, admin, etc) is appreciable for the v1 rollouts list.

**Comment by ryzokuken** [comment]
I have exams this week too, but I'd be free for discussion.
I'd love to talk about all the stuff you mentioned above, plus share my plans and ideas regarding issuing badges and getting the show on the road.

**Comment by amiller-gh** [comment]
Meeting issue created: https://github.com/nodejs/badges/issues/16

Let me know if you think we need anything else added to the agenda, however I think there is a lot to get through with those five issues alone!

**Comment by amiller-gh** [comment]
Per feedback in #16 we have moved the meeting to Thursday 15:00-16:00UTC 👍 We will have a very hard stop at 16:00 because the general CommComm meeting starts then, but it seems to be the best time for the majority

**Comment by amiller-gh** [comment]
Closing this issue because the first meeting ticket has been make 🙂 Lets continue any other meeting-specific discussion in #16.
